### ISSUE TITLE
Titanium dependency issue

### ISSUE THREAD

**Issue by zachsai** [RasaNovum/Timber_Frames#1]
The textures are messing up in jei
![image](https://user-images.githubusercontent.com/63996164/162332520-7420d059-d646-4bd6-bf7f-fa4be2135ae5.png)
Also, how do you get soul clay?

**Comment by xameryn** [comment]
The missing titanium texture issue occurs when the Timber Frames mod is not loaded so this is a Titanium or JEI issue. And Soul Clay is found in the Soul Sand Valley biome within the Nether inside Soul Sand and Soul Soil.

**Comment by zachsai** [comment]
I will link this thread in the titanium github for them to refer to
