### ISSUE TITLE
Could not initialize Broadknife particle class causing server disconnect

### ISSUE THREAD

**Issue by spektrumm** [RasaNovum/Timber_Frames#2]
**The Problemo**:
Pulling out a Broadknife once any timber frame blocks have been placed in the world causes an immediate disconnect.
On forge 1.18.2 server, neither server nor client crashed upon this issue, however client cannot reconnect as the same error gets thrown causing a disconnect.

On Mohist 1.18.2 preview, the server crashes with a crash report, but client does not crash.

**Reproduction**:
Boot 1.18.2 forge server
Connect as player
place timber frames blocks
pull out broadknife
bazinga

**Logs/Crash reports**:
[forge1.18.2 log file](https://github.com/RasaNovum/Timber_Frames/files/8458259/latest.log)
[mohist preview server crash file](https://github.com/RasaNovum/Timber_Frames/files/8458260/crash-2022-04-09_21.30.27-server.txt)

**versions**:
forge version: forge-1.18.2-40.0.44
mohist version: mohist preview 29 (mohist-1.18.2-40.0.40-29)
timber frame version: 1.18.2_1.1

**Comment by xameryn** [comment]
It just does that sometimes.

**Comment by xameryn** [comment]
Resolved in version 1.2.
