### ISSUE TITLE
CTM Causing Crash

### ISSUE THREAD

**Issue by yancypro** [RasaNovum/Timber_Frames#5]
This CTM crash does not occur until CTM is loaded. Optifine is not loaded, see crash report attached. Timber Frames by itself loads fine except a note that states: "The Timber Frame Mod requires CTM to fully function."
- This issue does not occur without the Timber Frames mod loaded.

[crash-2022-07-03_09.39.05-client.txt](https://github.com/RasaNovum/Timber_Frames/files/9034924/crash-2022-07-03_09.39.05-client.txt)

 - Minecraft Version: 1.18.2 
 - Forge Version: 1.18.2-forge-40.1.52
 - Timber Frames Version: Timber_Frames_1.18.2_1.3_CTM

**Comment by xameryn** [comment]
Does the crash still occur using Timber Frames version 1.4.1?

**Comment by yancypro** [comment]
I believe that's the one I have.

**Comment by xameryn** [comment]
The log and the version listed in your comment say you have version 1.3, try downloading the newest version for 1.18.2

**Comment by xameryn** [comment]
Will close this for now, if you're still having the problem with v1.4.1 I'll re-open the issue.
