### ISSUE TITLE
Rubidium causes flickering textures

### ISSUE THREAD

**Issue by ChefTheChefChef** [RasaNovum/Timber_Frames#8]
Before Reporting Bug:
- Make sure this issue does not occur without the Timber Frames mod loaded.
- Make sure your report is not a duplicate of another issue.
- Make sure your report is not a question, if you have a question contact us either on the CurseForge page or our provided socials.

**Describe the bug:**
Hello; I'm using Rubidium, Rubidium Extras and Rubidium Dynamic lighting - I'm not sure if this is the exact issue, but I'm encountering flickering with the textures on the frames when holding a torch or placing blocks near the frames.

**Steps To Reproduce (If Applicable):**
Install mods - Rubidium, Rubidium Extras, Rubidium Dynamic Lights, Timber Frames
Launch game (1.18.2)
Create world, place timber frames, equip a torch and walk around, or place blocks next to frames; they should flicker.

**Screenshots (If Applicable):**
![image](https://user-images.githubusercontent.com/11790731/190843469-4f0470f3-1eb5-4533-934c-90a711817cbc.png)

**Versions:**
 - Minecraft Version: 1.18.2
 - Forge Version: 40.1.69
 - Timber Frames Version: 1.5

**Comment by xameryn** [comment]
Hey, unfortunately this is [a known issue with Rubidium](https://github.com/Asek3/Rubidium/issues/160) which causes an incompatibility with CTM blocks (including Timber Frames blocks).

The flicker occurs whenever the block is updated, and Rubidium Dynamic Lighting seems to update the block whenever you move with a light source.

Until it's fixed you can bypass the issue by opening the ```rubidium-mixins.properties``` found in your config folder, and adding ```mixin.features.chunk_rendering=false``` to the file, this will resolve the flickering at the cost of some performance.
